<a href="https://colab.research.google.com/github/LEDesing/Deep-Learning-WPO/blob/main/WPO1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

### PyTorch Tensors

The deep learning terminology for a "matrix". In PyTorch, it is the basic structure to represent data

In [ ]:
#This is a 1-D Tensor
a = torch.tensor([2,2,1])
print(a)
# the shape of a Tensor "a".
print(a.shape) # or a.size()
# the data type of a Tensor "a".
print(a.dtype)

tensor([2, 2, 1])
torch.Size([3])
torch.int64


In [ ]:
#This is a 2-D Tensor
b = torch.tensor([[2,1],
                  [3,5],
                  [1,2]])
print(b)
print(b.shape)

tensor([[2, 1],
        [3, 5],
        [1, 2]])
torch.Size([3, 2])


In [ ]:
# Get the number of rows of b
print(b.shape[0])

# Get the number of columns of b
print(b.shape[1])

# number of elements
print(b.numel())

assert b.numel() == b.shape[0] * b.shape[1] # pour verifier une egalité.

3
2
6


In [ ]:
# Create a Float Tensor
b_float = torch.FloatTensor([[2,1,4],
                             [3,5,4],
                             [1,2,0]])

In [ ]:
# or convert the original b into float
b = b.float()
print(b)
print(b.dtype)

tensor([[2., 1.],
        [3., 5.],
        [1., 2.]])
torch.float32


In [ ]:
# statistics on a tensor

#Print the mean of all elements of tensor b.
print(b.mean())
#Print the sum of all elements of tensor b.
print(b.sum())
#Print the standard deviation of all elements tensor b.
print(b.std())

tensor(2.3333)
tensor(14.)
tensor(1.5055)


In [ ]:
# statistics across dimensions
print(b.mean(dim = 0))    # moyenne suivant les colones
print(b.mean(dim = 1))   # moyenne suivant les ligne
print(b.mean(dim = -1))   # moyenne suivant la derniere dimension.

tensor([2.0000, 2.6667])
tensor([1.5000, 4.0000, 1.5000])
tensor([1.5000, 4.0000, 1.5000])


In [ ]:
# transposing 2D tensors
print(b)
b = b.t()
print(b.shape)
print(b.size())

NameError: name 'b' is not defined

In [ ]:
# flattening a tensor into 1D
print(b)
print(b.shape)
b = b.reshape(-1)  # -1, its size can be inferred
print(b.shape)

tensor([[2., 3., 1.],
        [1., 5., 2.]])
torch.Size([2, 3])
torch.Size([6])


In [ ]:
# create a random 3D tensor with values sampled from the normal distribution with a mean of 0 and a std of 1
r1 = torch.randn(6,3,4)   # n stand for normal distribution (6 c'est la profondeur:  la 3eme dimension)

# create a random 3D tensor with values sampled from the uniform distribution from the range 0-1
r2 = torch.rand(6,4,3)

# transpose the 3D tensor r2 to match dimensions with r1
r2 = r2.permute(0,2,1) # pour trasposer un tenseur de dimension 3.;  0== je mentien la profondeur, 2, 1 pour transposer la matrice dim2
# en pratique 2 devien 1 et vice versa. (1 ==rows, 2==columns).

In [ ]:
# element-weise operations (addition, multiplication, subtraction)
print(r1 + r2)
print(r1 * r2)

In [ ]:
# absolute value
f = torch.randn(1,2)
print(f)
print(torch.abs(f))

In [ ]:
# tensor of 1s and 0s
ones = torch.ones(3,5)
print(ones)

zeros = torch.zeros(5,2) #zeros(colum, row)
print(zeros)

# add a scalar
zeros = zeros + 5
print(zeros)

In [ ]:
# random tensor with the shape and datatype of another tensor
v = torch.randn_like(ones)
print(v)

### Matrix Multiplications

Create any two random 2D tensors, and perform a matrix multiplication. Make sure the dimensions match! Use [torch.matmul](https://pytorch.org/docs/stable/generated/torch.matmul.html)

In [ ]:
### SOLUTION
t2D1 = torch.randn(3,3)
t2D2 = torch.rand(3,3)
mux  = t2D1*t2D2
print(mux)


tensor([[ 0.1380,  0.1951, -0.4190],
        [-0.2315, -0.0476, -0.4045],
        [ 0.0358,  0.3536,  0.4914]])


Print all the elements of the **first** column of the result

In [ ]:
### SOLUTION
print(mux[:,0])

tensor([ 0.1380, -0.2315,  0.0358])


Print any element (one only) from the resulting tensor. See [torch.item](https://pytorch.org/docs/stable/generated/torch.Tensor.item.html)

In [ ]:
### SOLUTION
print(mux.tolist())
print(mux[0,1])
print(mux[0,1].tolist())
print(mux[0,1].item())

[[0.137994185090065, 0.19510510563850403, -0.41902390122413635], [-0.23147739470005035, -0.04759873449802399, -0.4044612646102905], [0.03577583655714989, 0.3536339998245239, 0.49136000871658325]]
tensor(0.1951)
0.19510510563850403
0.19510510563850403


Now let's create a 4D Tensor called `g`

In [ ]:
g = torch.randn(6,7,2,4)

Reshape the tensor `g` to 3D to have the shape: (6,7,8). Use the [reshape](https://pytorch.org/docs/stable/generated/torch.reshape.html) function. Try two different ways of reshaping, including specifying -1. Verify that the two ways of rehaping are equivalent, using the `assert` function in Python

In [ ]:
### SOLUTION
h = g.reshape(6,7,8)
print(h.shape())

TypeError: 'torch.Size' object is not callable

Create a random 2D tensor, then extract its maximum value using [torch.max](https://pytorch.org/docs/stable/generated/torch.max.html)

In [ ]:
### SOLUTION

Now extract the maximum value and the index of that value, across the **columns**

In [ ]:
### SOLUTION

Now extract the maximum value and the index of that value, across the **rows**

In [ ]:
### SOLUTION

### Numpy Bridge

Define a random PyTorch Tensor of any size you want, and convert it into numpy using [.numpy](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html)

In [ ]:
### SOLUTION

Now convert back the numpy tensor to PyTorch, using [torch.from_numpy](https://pytorch.org/docs/stable/generated/torch.from_numpy.html)

In [ ]:
### SOLUTION

Move the PyTorch Tensor to the GPU. When training deep learning models, everything has to be on the GPU!

In [ ]:
# move the tensor to the GPU
a = torch.randn(5)
print(a.device)
CUDA = torch.cuda.is_available()
print(CUDA)
if CUDA:
    a = a.cuda()
    print(a.device)

### Tensor Concatenation

You can concatenate any two tensors along any dimension, using [torch.cat](https://pytorch.org/docs/stable/generated/torch.cat.html). Make sure that the two tensors you are concatenating match along the dimension you want to concatenate!

Define two 2D Tensors of random values. Afterwards, concatenate along the rows. Print the shape of the resulting tensor

In [ ]:
### SOLUTION

Define two 2D Tensors of random values. Afterwards, concatenate along the columns. Print the shape of the resulting tensor

In [ ]:
### SOLUTION

### Adding and Removing Dimensions

In many times, we need to add a dimension to be able to operate on Tensors. We will see many cases of this during the course. This is probably the most function we will use.

To add a dimension, the function is [unsqueeze](https://pytorch.org/docs/stable/generated/torch.unsqueeze.html). To remove a dimension, the function is [squeeze](https://pytorch.org/docs/stable/generated/torch.squeeze.html).

In [ ]:
a = torch.tensor([1, 2, 3, 4])

Add a dimension at the end. Print the shape

In [ ]:
a.shape
#unsqueesed.squeeze(1); #unsqueesed.squeeze(-1); #unsqueesed.squeeze(0);

torch.Size([4])

Add another dimension at the start. Print the shape

In [ ]:
### SOLUTION

Add another dimension at the start (one more time). Print the shape

In [ ]:
### SOLUTION

Remove the last dimension. Print the shape

In [ ]:
### SOLUTION

Remove all dimensions with a 1

In [ ]:
### SOLUTION

### Autograd (Automatic Differentiation) in PyTorch

Remember we need to tell PyTorch which gradients we want!
If we dont explicilty tell it, PyTorch will not track gradients!

Let's create some operations:

In [ ]:
x = torch.tensor([1., 2., 3., 4., 5.])
y = x**2
z = torch.sum(y)

Every Tensor has a `requires_grad` attrbiute which tells us if the tensor needs gradients. It also has a `grad_fn` attribute that tells you what the funtion is

In [ ]:
print(x.requires_grad)
print(z.grad_fn)

1. Now create the same tensor, but this time it should require gradients (gradients should be computed with respect to it). Perform the same operations as above on that Tensor

In [ ]:
### SOLUTION

2. Check the gradient function. Does PyTorch know how z was created? Did it record the computation?

In [ ]:
### SOLUTION

3. Check which tensors (`x`,`y`,`z`) requires_grad

In [ ]:
### SOLUTION

We can access the gradient of any tensor using the `grad` attribute

In [ ]:
print(x.grad)

As we see, it is `None`. The function `backward` computes the gradients

In [ ]:
z.backward()
print(x.grad)

Do the same thing (check the gradients) of `y`. What do you realize?

In [ ]:
### SOLUTION

`y` is an intermediate variable. PyTorch does NOT keep gradients of intermediate tensors in order to save memory. If we wanted the gradient with respect to `y`, we need to tell PyTorch to track it through the `retain_grad` function

In [ ]:
y.retain_grad()

But now if we find the gradient of `y`, we get an error.

In [ ]:
z.backward()

That is because the computation graph is destroyed after the backward call! You need to tell PyTorch that you want it to compute gradients w.r.t `y`, **before** you call the backward function. We can use the [retain grad](https://pytorch.org/docs/stable/generated/torch.Tensor.retain_grad.html) function for this

In [ ]:
### SOLUTION

**Note FYI:** You can also keep the graph (avoid PyTorch from destroying it after the backward call) using `retrain_graph = True` when calling the backward function. However, we will almost never use this.

the `detach` function tells PyTorch to forget the computation history. It is very helpful to free memory! Saves you 50% of the problems. It returns a copy of the tensor but with the computation history forgotten.

In [ ]:
x = torch.tensor([1., 2., 3., 4., 5.], requires_grad=True)
y = x * 2
z = torch.sum(y)
print(z.grad_fn)

Now forget the computation history of the variable `z`. Verify that it is forgotten using `grad_fn`

In [ ]:
### SOLUTION